import Head from 'next/head';
import { Portfolio, ActionType } from '@prisma/client';
import { fetchCoins } from '@/app/lib/data';

export default async function DashboardPage() {
  const coins = await fetchCoins();

  const formatActionType = (action: ActionType) => {
    switch (action) {
      case 'BUY':
        return 'bg-green-500 text-green-800';
      case 'HOLD':
        return 'bg-yellow-300 text-yellow-800';
      case 'SELL':
        return 'bg-red-400 text-red-800';
    }
  };
  return (
    <div>
      <Head>
        <title>CoinPouch</title>
        <meta
          name="description"
          content="Generated by create next app. An application to track coins!"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="my- my-36 h-auto">
        <div className="container mx-auto max-w-screen-lg px-4">
          <h1 className="text-3xl mb-5 font-bold tracking-wide text-white">
            Portfolio
          </h1>
          <section className="flex flex-col">
            <div className="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
              <div className="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div className="shadow overflow-hidden border-b border-gray-800 rounded-lg">
                  <table className="min-w-full divide-y divide-gray-800 ">
                    <thead className="bg-gray-800">
                      <tr>
                        <th
                          scope="col"
                          className="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"
                        >
                          Symbol
                        </th>
                        <th
                          scope="col"
                          className="px-6 py-3 text-left text-xs font-medium text-gray-300 uppercase tracking-wider"
                        >
                          Action
                        </th>
                      </tr>
                    </thead>
                    <tbody className="bg-gray-700 divide-y divide-gray-500">
                      {coins.map((item) => (
                        <tr key={item.id}>
                          <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-white">
                            {item.symbol}
                          </td>

                          <td className="px-6 py-4 whitespace-nowrap capitalize">
                            <span
                              className={`flex-shrink-0 inline-block px-2 py-0.5 text-xs font-medium rounded-full ${formatActionType(
                                item.actionType
                              )}`}
                            >
                              {item.actionType.toLowerCase()}
                            </span>
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}
