import Head from 'next/head';
import toast, { Toaster } from 'react-hot-toast';

export default function Home() {
  return (
    <main>
      <div>
        <Head>
          <title>CoinPouch</title>
          <meta
            name="description"
            content="Generated by create next app. An application to track coins!"
          />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <section>
          <p className="font-bold">Welcome to CoinPouch!</p>
        </section>
      </div>
    </main>
  );
}
