import Head from 'next/head';
// import { motion } from 'framer-motion';
// import { useForm } from 'react-hook-form';
// import toast, { Toaster } from 'react-hot-toast';

export default function Home() {
  return (
    <main>
      <Head>
        <title>CoinPouch</title>
        <meta
          name="description"
          content="Generated by create next app. An application to track coins!"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-md mx-auto px-4">
        <h1 className="font-bold text-3xl md:text-4xl text-white tracking-wide mb-10 text-center">
          Submit Your Feedback!
        </h1>

        <form className="grid grid-cols-1 gap-y-6 shadow-lg p-10 bg-[#131415] rounded-lg">
          <div className="relative">
            <label htmlFor="symbol" className="sr-only">
              symbol
            </label>
            <input
              id="symbol"
              name="symbol"
              type="text"
              className={`block w-full shadow-sm py-3 text-white px-4 mb-2 bg-[#131415] placeholder-gray-500   border-gray-700 rounded-md `}
              placeholder="Symbol"
            />
          </div>
        </form>
      </div>
    </main>
  );
}
