import Head from 'next/head';
import { createCoin } from '@/app/lib/actions';
// import { motion } from 'framer-motion';
// import { useForm } from 'react-hook-form';
// import toast, { Toaster } from 'react-hot-toast';

export default function Home() {
  return (
    <main>
      <Head>
        <title>CoinPouch</title>
        <meta
          name="description"
          content="Generated by create next app. An application to track coins!"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="max-w-md mx-auto px-4">
        <h1 className="font-bold text-3xl md:text-4xl text-white tracking-wide mb-10 text-center">
          Add a coin!
        </h1>

        <form
          action={createCoin}
          className="grid grid-cols-1 gap-y-6 shadow-lg p-10 bg-[#131415] rounded-lg"
        >
          <div className="relative">
            <label htmlFor="symbol" className="sr-only">
              symbol
            </label>
            <input
              id="symbol"
              name="symbol"
              type="text"
              className={`block w-full shadow-sm py-3 text-white px-4 mb-2 bg-[#131415] placeholder-gray-500   border-gray-700 rounded-md `}
              placeholder="Symbol"
            />
          </div>

          <div>
            <label htmlFor="actiontype" className="sr-only">
              Action Type
            </label>
            <select
              id="actionType"
              name="actionType"
              className="mt-1 block w-full pl-3 pr-10 py-2 text-base bg-[#131415] placeholder-gray-500 text-white focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm rounded-md"
              defaultValue="BUY"
            >
              <option>BUY</option>
              <option>SELL</option>
              <option>HOLD</option>
            </select>
          </div>

          <div>
            <button
              type="submit"
              className="w-full justify-center py-3 px-6 border border-transparent shadow-sm text-base font-medium rounded-md text-white bg-blue-800 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
            >
              Submit
            </button>
          </div>
        </form>
      </div>
    </main>
  );
}
